<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Service;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;

class AdminServiceController extends Controller
{
    public function toggleVisibility(Request $request, $id)
    {
        try {
            $service = Service::findOrFail($id);
            // Toggle the visibility: if it's 1, make it 0; if it's 0, make it 1
            $service->visibility = $service->visibility ? 0 : 1;
            $service->save();
            
            return redirect()->route('admin.service.index')->with('success', 'Service visibility updated successfully.');
        } catch (\Exception $e) {
            Log::error('Service visibility toggle error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors('Could not update Service visibility.');
        }
    }

    public function index()
    {
        $services = Service::all();
        return view('admin.crud.services.index', compact('services'));
    }

    public function add()
    {
        return view('admin.crud.services.add');
    }

    public function store(Request $request)
    {
        try {
            $request->validate([
                'heading' => 'required|string|max:255',
                'description' => 'required',
                'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'bg_image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'icon' => 'nullable|string|max:255',
                'visibility' => 'nullable|integer',
            ]);

            $validatedData = $request->only(['heading', 'description', 'icon', 'visibility']);

            // Handle image upload
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageName = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('uploads/services'), $imageName);
                $validatedData['image'] = 'uploads/services/' . $imageName;
            }

            // Handle background image upload
            if ($request->hasFile('bg_image')) {
                $bgImage = $request->file('bg_image');
                $bgImageName = time() . '_bg_' . $bgImage->getClientOriginalName();
                $bgImage->move(public_path('uploads/services'), $bgImageName);
                $validatedData['bg_image'] = 'uploads/services/' . $bgImageName;
            }

            Log::info('Validated Service data:', $validatedData);

            // Slug will be auto-generated by the model
            $service = Service::create([
                'heading' => $validatedData['heading'],
                'description' => $validatedData['description'],
                'image' => $validatedData['image'] ?? null,
                'bg_image' => $validatedData['bg_image'] ?? null,
                'icon' => $validatedData['icon'],
                'visibility' => $validatedData['visibility'] ?? 1,
            ]);

            Log::info('Service created successfully:', ['id' => $service->id, 'slug' => $service->slug]);

            return redirect()->route('admin.service.index')->with('success', 'Service added successfully.');
        } catch (\Exception $e) {
            Log::error('Error while creating Service:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function edit($id)
    {
        $service = Service::findOrFail($id);
        return view('admin.crud.services.edit', compact('service'));
    }

    public function update(Request $request, $id)
    {
        try {
            $request->validate([
                'heading' => 'required|string|max:255',
                'description' => 'required',
                'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'bg_image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'icon' => 'nullable|string|max:255',
                'visibility' => 'nullable|integer',
            ]);

            $service = Service::findOrFail($id);
            
            // Check if heading has changed to regenerate slug
            $headingChanged = $service->heading !== $request->heading;
            
            $updateData = [
                'heading' => $request->heading,
                'description' => $request->description,
                'icon' => $request->icon,
                'visibility' => $request->visibility ?? 1,
            ];

            // If heading changed, clear slug to trigger auto-generation
            if ($headingChanged) {
                $updateData['slug'] = null;
            }

            // Handle image upload
            if ($request->hasFile('image')) {
                // Delete old image if exists
                if ($service->image && file_exists(public_path($service->image))) {
                    unlink(public_path($service->image));
                }
                
                $image = $request->file('image');
                $imageName = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('uploads/services'), $imageName);
                $updateData['image'] = 'uploads/services/' . $imageName;
            }

            // Handle background image upload
            if ($request->hasFile('bg_image')) {
                // Delete old background image if exists
                if ($service->bg_image && file_exists(public_path($service->bg_image))) {
                    unlink(public_path($service->bg_image));
                }
                
                $bgImage = $request->file('bg_image');
                $bgImageName = time() . '_bg_' . $bgImage->getClientOriginalName();
                $bgImage->move(public_path('uploads/services'), $bgImageName);
                $updateData['bg_image'] = 'uploads/services/' . $bgImageName;
            }

            $service->update($updateData);

            Log::info('Service updated successfully:', ['id' => $service->id, 'slug' => $service->fresh()->slug]);

            return redirect()->route('admin.service.index')->with('success', 'Service updated successfully.');
        } catch (\Exception $e) {
            Log::error('Service update error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    public function destroy($id)
    {
        try {
            $service = Service::findOrFail($id);
            
            // Delete associated files
            if ($service->image && file_exists(public_path($service->image))) {
                unlink(public_path($service->image));
            }
            
            if ($service->bg_image && file_exists(public_path($service->bg_image))) {
                unlink(public_path($service->bg_image));
            }
            
            $service->delete();
            return redirect()->route('admin.service.index')->with('success', 'Service deleted successfully.');
        } catch (\Exception $e) {
            Log::error('Service delete error:', ['message' => $e->getMessage()]);
            return redirect()->back()->withErrors('Could not delete Service.');
        }
    }
}
